POST   http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhY2hoIiwiaWQiOiI2MGI3YzVlNjJiMDQxNzBlYTRkY2IzYjMiLCJpYXQiOjE2MjI2NTY5MTh9.7C_g2PKlap9KgKkC79kqT4IsdgA3ny3pFZkRqyUQ3ss

{
    "title": "Machine;adsdkl;kas learning",
    "author": "Phu Pasdhl;kl;ssam",
    "url": "http://rekl;asdalssaddress.com",
    "likes": 32
}
###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/obpApi/grantView
Content-Type: application/json

{
    "bank_id": "gh.29.fi",
    "id": "9c0502d7-c076-424d-a2bc-cb689edb4734"
}
###
POST   http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "BachPham",
    "name": "Bach Pham",
    "password": "bach90"
}
###
POST   http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "BachPham",
    "password": "bach90"
}

###
PUT http://127.0.0.1:3001/api/obpApi/save/60db274832df2213fc9346ed
